

---CREATE DATAWAREHOUSE
CREATE DATABASE DATAWAREHOUSE;
GO
----CREATE BRONZE SCHEMA
CREATE SCHEMA bronze;
GO
---CREATE SILVER SCHEMA
CREATE SCHEMA silver;
---CREATE GOLD SCHEMA
GO
CREATE SCHEMA gold;
